### ISSUE TITLE
is this work at bsc? 

### ISSUE THREAD

**Issue by kugimiya530** [Twerewolf/go-ethereum-modified#1]
any performance different from   original bsc geth?

**Comment by Twerewolf** [comment]
您好！您的邮件已收到，我会尽快回复您。谢谢！

**Comment by Twerewolf** [comment]
it's basically for my personal study purpose, and it's forked from go-ethereum, not bsc. i'm working on the storage and p2p network, maybe you can compare the go-ethereum and bsc project for performance diff. BTW, bsc is customized according to go-ethereum.

**Comment by kugimiya530** [comment]
Alright thx for answer

sleep well ***@***.***> 於 2022年5月27日 週五 11:52 寫道：
